networks:
  my_network:
    driver: bridge

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    networks:
      - my_network

  app:
    build: .
    ports:
      - 4000:3000
    environment:
      APP_NAME: DockerTesting
      PORT: 3000
      MONGO_URL: mongodb://mongo_db:27017/signUpm
    depends_on:
      - mongo_db
    networks:
      - my_network 

volumes:
  mongo_db: {}
